version: "3.9"

services:

  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "8888:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8443
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"

    command: start-dev

    ports:
      - "8443:8080"

    depends_on:
      - postgres

  inference:
    build:
      context: .
      dockerfile: docker/Dockerfile

    environment:
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}

    ports:
      - "8000:8000"

    volumes:
      - ./models:/app/models

    depends_on:
      - keycloak